name: Install Packages
description: Uses the distro’s package manager to install packages. Supports Debian, Ubuntu, RHEL, Photon, CBL-Mariner, and derived OSes. For Alpine, install bash first.
author: Ruslan Bahna
branding:
  icon: package
  color: blue
inputs:
  packages:
    description: "Space-delimited list of packages to install"
    required: true
runs:
  using: "composite"
  steps:
    - name: Check for Linux
      if: ${{ runner.os != 'Linux' }}
      uses: actions/github-script@v6
      with:
        script: core.setFailed('This action only supports Linux operating systems.')

    - name: Check for Bash
      run: |
        echo "Checking if bash exists. If you are running Alpine and do not have bash, run: apk add bash"
        bash --version
      shell: sh

    - run: |
        if [ -x "$(command -v apt-get)" ]; then
          # Ubuntu and Debian package manager. Replaced dpkg as default.
          # For explanation of unusual switches, see https://askubuntu.com/questions/258190/how-to-make-apt-get-install-less-noisy
          # Otherwise, apt-get clogs up the logs
          DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends --quiet --yes -o=Dpkg::Use-Pty=0 install coreutils build-essentials
        elif [ -x "$(command -v apk)" ]; then
          # Alpine package manager.
          apk update
          apk add coreutils build-essentials
        elif [ -x "$(command -v tdnf)" ]; then
          # CBL-Mariner and Photon package manager. Stripped down version of dnf.
          currentVersion="$(tdnf --version)"
          requiredVersion="3.5.0"
          # Explanation of if statement: https://unix.stackexchange.com/questions/285924/how-to-compare-a-programs-version-in-a-shell-script
          if [ "$(printf '%s\n' "$requiredVersion" "$currentVersion" | sort -V | head -n1)" = "$requiredVersion" ]; then
          # --nodocs argument is not supported, but it is supported as a flag
            tdnf --setopt=tsflags=nodocs --assumeyes install coreutils build-essentials
          else
            tdnf --assumeyes install coreutils build-essential
          fi
        elif [ -x "$(command -v microdnf)" ]; then
          # RHEL minimal package manager. Stripped down version of dnf.
          microdnf --setopt=install_weak_deps=0 --nodocs --assumeyes install coreutils build-essentials
        elif [ -x "$(command -v dnf)" ]; then
          # RHEL and Fedora package manager. Replaced yum and rpm as default.
          dnf --setopt=install_weak_deps=false --nodocs --assumeyes install coreutils build-essentials
        elif [ -x "$(command -v rpm)" ]; then
          # Fallback package manager. Superseded by more modern package managers.
          rpm --install --excludedocs coreutils build-essentials
        else
          echo "This distro's package manager is not currently supported"
          exit 1
        fi

      shell: bash
