name: test

on:
  push:
    paths-ignore:
      - '.vscode/**'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - '**/*.md'
  workflow_run:
    workflows: ["Update Major Release Tag"]
    types: [completed]

jobs:
  test-container-image-size:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Container Registry
      run: docker login ghcr.io --username ${{ github.repository_owner }} --password ${{ secrets.GHCR_TOKEN }}
      
    - name: Check out code
      uses: actions/checkout@v4

    - name: pull image
      run: docker pull ghcr.io/ruslanbahna/hardened-images/hardened-node:photon-5.0.17

    - name: test image size
      uses: ruslanbahna/reusable-actions/container-image-size@v0.0.2
      with: 
        built-image: docker pull ghcr.io/ruslanbahna/hardened-images/hardened-node:photon-5.0.17
        base-image: ubuntu:latest


