name: test

on:
  push:
    paths-ignore:
      - '.vscode/**'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - '**/*.md'
  workflow_run:
    workflows: ["Update Major Release Tag"]
    types: [completed]

jobs:
  test-container-image-size:
    runs-on: ubuntu-latest
    steps:
      - name: Log into Container Registry
        uses: docker/login-action@v3
        with:
          regisrty: ghcr.io/ruslanbahna/hardened-images
          username: ${{github.repository_owner}}
          password: ${{secrets.GHCR_TOKEN}}
      
      - name: Check out code
        uses: actions/checkout@v4

      - name: pull image
        run: 
