name: test

on:
  push:
    paths-ignore:
      - '.vscode/**'
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - '**/*.md'
  workflow_run:
    workflows: ["Update Major Release Tag"]
    types: [completed]

jobs:
  test-container-image-size:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Container Registry
      run: docker login ghcr.io --username ${{ github.repository_owner }} --password ${{ secrets.GHCR_TOKEN }}
      
    - name: Check out code
      uses: actions/checkout@v4


